// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwvZbxq-9R5EmEUMvCmensLhHzGE4qhx0',
    appId: '1:170527388370:web:53cc8b7a3bbf5bbe11730b',
    messagingSenderId: '170527388370',
    projectId: 'capstone-3e283',
    authDomain: 'capstone-3e283.firebaseapp.com',
    storageBucket: 'capstone-3e283.firebasestorage.app',
    measurementId: 'G-C7XX5SWFQW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB308bJ9_fX0MBfjDjgBn6Ml-zkWIvZgQQ',
    appId: '1:170527388370:android:2b99c1b08f6fd26411730b',
    messagingSenderId: '170527388370',
    projectId: 'capstone-3e283',
    storageBucket: 'capstone-3e283.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRkgsPqFvsZ5Xoq_yIYGxlufzr-jecdtA',
    appId: '1:170527388370:ios:a2eef2f96f7fa8c911730b',
    messagingSenderId: '170527388370',
    projectId: 'capstone-3e283',
    storageBucket: 'capstone-3e283.firebasestorage.app',
    iosBundleId: 'com.example.myNewFoodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRkgsPqFvsZ5Xoq_yIYGxlufzr-jecdtA',
    appId: '1:170527388370:ios:a2eef2f96f7fa8c911730b',
    messagingSenderId: '170527388370',
    projectId: 'capstone-3e283',
    storageBucket: 'capstone-3e283.firebasestorage.app',
    iosBundleId: 'com.example.myNewFoodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwvZbxq-9R5EmEUMvCmensLhHzGE4qhx0',
    appId: '1:170527388370:web:072e2d64657c4d4a11730b',
    messagingSenderId: '170527388370',
    projectId: 'capstone-3e283',
    authDomain: 'capstone-3e283.firebaseapp.com',
    storageBucket: 'capstone-3e283.firebasestorage.app',
    measurementId: 'G-YPVRMBYLLP',
  );
}
